### ISSUE TITLE
Excessive output from mermaid example from README in CLI on Windows

### ISSUE THREAD

**Issue by nathanjmcdougall** [ben-denham/labtech#14]
Running this mermaid example from the README from the CLI (rather than an interactive IPython session) seems to spam the console with `<IPython.core.display.Markdown object>` (12 times total).

Running things from the CI in #13, this doesn't seem to happen on Linux.

**Comment by ben-denham** [comment]
Good catch, I've improved `display_task_diagram` to actually check you're in an IPython session (rather than just checking that you have `IPython` installed) in ef08cfee7f. I'm not sure whether there will still be an issue in an `IPython` CLI session on Windows, but if it is, then that sounds like it would be an IPython issue.
